//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCARI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosi
    {
        public int DiagnosisId { get; set; }
        public int UserId { get; set; }
        public string DiagnosisName { get; set; }
        public System.DateTime OnsetDate { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
