//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCARI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Immunization
    {
        public int ImmunizationId { get; set; }
        public int UserId { get; set; }
        public System.DateTime ImmunizationDate { get; set; }
        public string FullVaccineName { get; set; }
        public string Cardinality { get; set; }
        public Nullable<int> AdministeredBy { get; set; }
        public string Reaction { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string NextVaccineName { get; set; }
        public Nullable<System.DateTime> NextVaccineDate { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual User User { get; set; }
    }
}
