//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCARI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabAttachment
    {
        public int LabAttachmentId { get; set; }
        public int LabId { get; set; }
        public string ReportType { get; set; }
        public byte[] ResportAttachment { get; set; }
    
        public virtual Lab Lab { get; set; }
    }
}
